version: '3.1'

services:
  
  client:
    command: yarn build
    volumes:
      - ./client/build:/home/app/server/build
  
  server:
    environment:
      DEPLOYMENT_TYPE: 'PRODUCTION'
  
  proxy:
    volumes:
      - ./proxy/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./client/build:/usr/share/nginx/html