DEBUG = True
DEFAULT_TAG = "GAME"

# Card values
CARD_ONE = 1
CARD_TWO = 2
CARD_THREE = 3
CARD_FOUR = 4
CARD_FIVE = 5
CARD_SIX = 6
CARD_SEVEN = 7
CARD_EIGHT = 8
CARD_NINE = 9
CARD_ZERO = 0

CARD_SKIP = "SKIP"
CARD_REVERSE = "REVERSE"
CARD_DRAW_TWO = "DRAW2"

CARD_WILD = "WILD"
CARD_DRAW_FOUR = "DRAW4"