DEBUG = True
DEFAULT_TAG = "GAME"

# Game context keys
CONTEXT_PLAYERS = "PLAYERS"
CONTEXT_WINNER = "WINNER"
CONTEXT_NUM_TURNS = "NUM_TURNS"
CONTEXT_GAME_TIME = "GAME_TIME"
CONTEXT_PLAYER_CARDS_PLAYED = "PLAYER_CARDS_PLAYED"
CONTEXT_CURRENT_ACTION = "ACTIVE_ACTION"

# Text input choices
CHOICE_DRAW_CARD = "draw a card"

# Card values
CARD_ZERO = 0
CARD_ONE = 1
CARD_TWO = 2
CARD_THREE = 3
CARD_FOUR = 4
CARD_FIVE = 5
CARD_SIX = 6
CARD_SEVEN = 7
CARD_EIGHT = 8
CARD_NINE = 9
CARD_VALUES = [CARD_ZERO, CARD_ONE, CARD_TWO, CARD_THREE, CARD_FOUR, CARD_FIVE, CARD_SIX, CARD_SEVEN, CARD_EIGHT, CARD_NINE]
# Card colors
CARD_BLUE = "BLUE"
CARD_RED = "RED"
CARD_PURPLE = "PURPLE"
CARD_YELLOW = "YELLOW"
CARD_COLORS = [CARD_BLUE, CARD_RED, CARD_PURPLE, CARD_YELLOW]

CARD_SKIP = "SKIP"
CARD_REVERSE = "REVERSE"
CARD_DRAW_TWO = "DRAW2"

CARD_WILD = "WILD"
CARD_DRAW_FOUR = "DRAW4"